(function(){
  let forums=[],threads=[],me={signedIn:false,permissions:[]},activeForumId=null;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v||'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  async function jsonFetch(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||`Request failed (${r.status}).`);return d;}
  function has(slug){const p=me.permissions||[];return p.includes(slug)||p.includes('admin_dashboard')||p.includes('moderate_posts');}
  function canPost(){return !!me.signedIn&&has('create_posts');}
  function canEdit(x){return !!me.signedIn&&((x.author_id===me.user?.id&&has('edit_own_posts'))||has('moderate_posts'));}
  function canDelete(x){return !!me.signedIn&&((x.author_id===me.user?.id&&has('delete_own_posts'))||has('moderate_posts'));}
  function formatDate(v){if(!v)return '';const d=new Date(String(v).includes('T')?v:String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?v:d.toLocaleString();}
  function setStatus(id,msg,type=''){const el=$(id);if(!el)return;el.textContent=msg;el.className='forum-submit-status '+type;}
  async function uploadImage(file,statusId){if(!file)return '';const fd=new FormData();fd.append('file',file);setStatus(statusId,'Uploading image…','working');const d=await jsonFetch('/api/media/upload',{method:'POST',body:fd});return d.asset?.url||'';}
  function imageHtml(url,alt='Forum attachment'){return url?`<a class="forum-post-image-link" href="${esc(url)}" target="_blank" rel="noopener"><img class="forum-post-image" src="${esc(url)}" alt="${esc(alt)}" loading="lazy"></a>`:'';}
  async function init(){
    try{me=await jsonFetch('/api/me');}catch{me={signedIn:false,permissions:[]};}
    if(me.signedIn){const u=me.user||{};$('forumLoginStatus').textContent=`Signed in as ${u.ingame_name||u.username||'Guild Member'} • ${u.rank_name||'Member'}`;$('forumSigninHelp').hidden=true;}
    else{$('forumLoginStatus').textContent='Browsing as Guest • read only';$('forumSigninHelp').hidden=false;}
    $('threadComposer').hidden=!canPost();bindUploadPreview('threadImage','threadImageName','threadImagePreview');await loadForums();
  }
  function bindUploadPreview(inputId,nameId,previewId){const input=$(inputId);if(!input)return;input.addEventListener('change',()=>{const f=input.files?.[0];$(nameId).textContent=f?f.name:'PNG, JPG, WEBP, or GIF • 10 MB max';const prev=$(previewId);if(!f){prev.hidden=true;prev.innerHTML='';return;}const url=URL.createObjectURL(f);prev.hidden=false;prev.innerHTML=`<img src="${url}" alt="Selected image preview">`;});}
  async function loadForums(){try{const d=await jsonFetch('/api/forums/list');forums=d.forums||[];renderForums();}catch(e){$('forumGrid').innerHTML=`<article class="notice-card"><p class="error">${esc(e.message)}</p></article>`;}}
  function renderForums(){const grid=$('forumGrid');grid.innerHTML='';forums.forEach(f=>{const card=document.createElement('article');card.className='forum-card forum-type-'+esc(f.type);card.innerHTML=`<div class="forum-card-glow"></div><div class="forum-card-head"><span class="forum-icon">${f.icon||'💬'}</span><span class="forum-badge">${esc(f.type)}</span></div><h3>${esc(f.title)}</h3><p>${esc(f.description||'')}</p><div class="forum-card-foot"><button class="secondary-btn open-forum" type="button">Enter Forum</button><span class="forum-post-count">${Number(f.post_count||0)} posts</span></div>`;card.querySelector('button').addEventListener('click',()=>openForum(f.id));grid.appendChild(card);});}
  async function openForum(id){activeForumId=id;const f=forums.find(x=>x.id===id);if(!f)return;$('readerType').textContent=f.type+' forum';$('readerTitle').textContent=f.title;$('readerDescription').textContent=f.description||'';$('forumReader').hidden=false;$('threadComposer').hidden=!canPost();await loadThreads(id);$('forumReader').scrollIntoView({behavior:'smooth',block:'start'});}
  async function loadThreads(id){const list=$('threadList');list.innerHTML='<p class="muted">Loading transmissions…</p>';try{const d=await jsonFetch('/api/forums/threads?forum_id='+encodeURIComponent(id));threads=d.threads||[];renderThreads();}catch(e){list.innerHTML=`<p class="error">${esc(e.message)}</p>`;}}
  function userBadge(x){return `<div class="forum-user-chip" style="--user-color:${esc(x.author_color||'#bffcff')}"><span class="forum-user-dot"></span><div><strong>${esc(x.author_name||'Member')}</strong><small>${esc(x.rank_name||'Member')}</small></div></div>`;}
  function renderThreads(){const list=$('threadList');if(!threads.length){list.innerHTML='<div class="empty-forum-card"><h3>No transmissions yet.</h3><p>Start the first conversation for this forum.</p></div>';return;}list.innerHTML='';threads.forEach(t=>{const replies=Array.isArray(t.replies)?t.replies:[];const item=document.createElement('article');item.className='thread-item game-thread';item.innerHTML=`<div class="thread-accent"></div><div class="thread-topline"><div>${userBadge(t)}<h3>${esc(t.title)}</h3><small>${formatDate(t.created_at)}</small></div><span class="reply-count">${replies.length} ${replies.length===1?'reply':'replies'}</span></div><div class="thread-body">${esc(t.body).replace(/\n/g,'<br>')}${imageHtml(t.image_url,t.title)}</div><div class="reply-list">${replies.length?replies.map(r=>`<div class="reply-item" data-reply-id="${esc(r.id)}">${userBadge(r)}<div class="reply-meta"><span>${formatDate(r.created_at)}</span></div><div class="reply-body">${esc(r.body).replace(/\n/g,'<br>')}${imageHtml(r.image_url,'Reply attachment')}</div></div>`).join(''):'<p class="muted reply-empty">No replies yet.</p>'}</div>${canPost()?`<div class="reply-composer modern-reply-composer"><textarea data-reply-body="${esc(t.id)}" placeholder="Reply to this transmission…"></textarea><label class="mini-upload">📎<input data-reply-file="${esc(t.id)}" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label><button class="secondary-btn reply-send" type="button" data-reply-thread="${esc(t.id)}">Send</button><span class="reply-status" data-reply-status="${esc(t.id)}"></span></div>`:''}`;
    if(canEdit(t)||canDelete(t)){const a=document.createElement('div');a.className='forum-actions';if(canEdit(t)){const b=document.createElement('button');b.className='secondary-btn';b.textContent='Edit';b.onclick=()=>editThread(t);a.appendChild(b);}if(canDelete(t)){const b=document.createElement('button');b.className='danger-btn';b.textContent='Delete';b.onclick=()=>deleteThread(t);a.appendChild(b);}item.appendChild(a);}item.querySelectorAll('[data-reply-thread]').forEach(b=>b.onclick=()=>createReply(b.dataset.replyThread));list.appendChild(item);});}
  async function createReply(id){const box=document.querySelector(`[data-reply-body="${CSS.escape(id)}"]`),file=document.querySelector(`[data-reply-file="${CSS.escape(id)}"]`)?.files?.[0],status=document.querySelector(`[data-reply-status="${CSS.escape(id)}"]`),body=box?.value.trim()||'';if(!body&&!file)return;if(status)status.textContent='Saving…';try{const image_url=await uploadImage(file,'missing-status');await jsonFetch('/api/forums/reply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({thread_id:id,body,image_url})});if(box)box.value='';await loadThreads(activeForumId);}catch(e){if(status)status.textContent=e.message;alert(e.message);} }
  async function createThread(){if(!canPost()||!activeForumId)return;const title=$('threadTitle').value.trim(),body=$('threadBody').value.trim(),file=$('threadImage').files?.[0];if(!title||(!body&&!file)){setStatus('threadPostStatus','Add a title and a message or image.','error');return;}const btn=$('createThreadBtn');btn.disabled=true;setStatus('threadPostStatus','Saving post…','working');try{const image_url=await uploadImage(file,'threadPostStatus');await jsonFetch('/api/forums/threads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({forum_id:activeForumId,title,body,image_url})});$('threadTitle').value='';$('threadBody').value='';$('threadImage').value='';$('threadImagePreview').hidden=true;$('threadImagePreview').innerHTML='';$('threadImageName').textContent='PNG, JPG, WEBP, or GIF • 10 MB max';setStatus('threadPostStatus','Post published successfully.','success');await loadForums();await loadThreads(activeForumId);}catch(e){setStatus('threadPostStatus',e.message||'Could not save post. Your draft is still here.','error');}finally{btn.disabled=false;}}
  async function editThread(t){const title=prompt('Edit post title:',t.title);if(title===null)return;const body=prompt('Edit post message:',t.body);if(body===null)return;try{await jsonFetch('/api/forums/threads',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:t.id,title,body,image_url:t.image_url||''})});await loadThreads(activeForumId);}catch(e){alert(e.message);}}
  async function deleteThread(t){if(!confirm('Delete this post and all replies?'))return;try{await jsonFetch('/api/forums/threads?id='+encodeURIComponent(t.id),{method:'DELETE'});await loadForums();await loadThreads(activeForumId);}catch(e){alert(e.message);}}
  $('createThreadBtn')?.addEventListener('click',createThread);$('closeForumBtn')?.addEventListener('click',()=>{$('forumReader').hidden=true;activeForumId=null;window.scrollTo({top:$('forumGrid').offsetTop-120,behavior:'smooth'});});document.addEventListener('DOMContentLoaded',init);
})();
